### ISSUE TITLE
markers.txt

### ISSUE THREAD

**Issue by Elena983** [MattHodgman/mcmicro-flowSOM#5]
Hi
I create the text file markers.txt with markers in each row for the clusterization in each row.
But it gives permanently the error 'couldn’t find the file'

The string in yml file
options:
  flowsom: -m /Users/m/Desktop/flowsom/markers.txt -n 15

**Comment by ArtemSokolov** [comment]
Hi @Elena983,

It looks like you are running this through MCMICRO.
Can you try changing your `params.yml` to the following:

```
workflow:
  flowsom-model: /Users/m/Desktop/flowsom/markers.txt
options:
  flowsom: -n 15
modules:
  downstream:
    -
      name: flowsom
      model: -m
```

Short explanation: Nextflow creates a separate work directory for each process and stages only the input files it knows about in that directory. There is nothing to tell Nextflow that `/Users/m/Desktop/flowsom/markers.txt` is another file and not just an arbitrary string, so that file never gets staged or exposed to the flowsom container.

We have a mechanism where users can provide their own models to ilastik (https://mcmicro.org/troubleshooting/faq.html#q-how-do-i-run-mcmicro-with-my-own-ilastik-model). We can make use of that same mechanism to specify additional files for other processes. In this case, we are saying that `markers.txt` is a model file for flowsom, and that flowsom should use its model files with `-m`. We can then remove the reference to this file from `options`.

MCMICRO should now properly stage this file in flowsom's work directory, but let me know if this doesn't work.

**Comment by Elena983** [comment]
Many thanks for the answer, but there is an error

ERROR ~ Unrecognized parameter flowsom-model

If that possible run the downstream analysis as
`start-at: downstream `

to avoid each time running the segmentation

**Comment by ArtemSokolov** [comment]
I just added `flowsom-model` to the list of valid parameters: https://github.com/labsyspharm/mcmicro/commit/b80ca4244ac55b99031290d21ce10f8ce6507e63

Can you pull the latest version with `nextflow pull labsyspharm/mcmicro` and try again?

Should be no problem to have `start-at: downstream`.

**Comment by Elena983** [comment]
Could you please do the same model for the fastpg.
How to write then both of them correctly in params?

and thing with downloading from `start-at: downstream` is blank
![image](https://github.com/labsyspharm/mcmicro-flowSOM/assets/68946912/54d487fd-4798-4ac4-abca-a675f67be616)

**Comment by Elena983** [comment]
Hi Artem
run with the new params (model)
the new error recieved
![image](https://github.com/labsyspharm/mcmicro-flowSOM/assets/68946912/37d228fd-3f6d-47fd-bcf5-7a3e82c745e1)

**Comment by ArtemSokolov** [comment]
Hi @Elena983,

I fixed a small bug and added `fastpg-model` and `scanpy-model` to the list of recognizable parameters.
(Please use `nextflow pull labsyspharm/mcmicro` to get the latest update.)
I was able to run all three methods (fastpg, scanpy and flowsom) using the following `params.yml` with exemplar-001:

```
workflow:
  stop-at: downstream
  downstream: [fastpg, scanpy, flowsom]
  fastpg-model: /workspace/markers.txt
  scanpy-model: /workspace/markers.txt
  flowsom-model: /workspace/markers.txt
options:
  fastpg: -k 20
  scanpy: -k 20
  flowsom: -n 10
modules:
  downstream:
  - name: fastpg
    model: -m
  - name: scanpy
    model: -m
  - name: flowsom
    model: -m
```
I verified that it correctly passes the file I made (`/workspace/markers.txt`) to all modules using `-m`.

I can't seem to replicate your other issue of `start-at: downstream` giving an empty run. When I add `start-at: downstream` to my `workflow:` parameters, MCMICRO only reruns these three modules and nothing else.

**Comment by Elena983** [comment]
Could you check start from modules with my params  and my '.csv' in the 'quantification' folder, please
[markers.csv](https://github.com/labsyspharm/mcmicro-flowSOM/files/13041207/markers.csv)
[CRC--mesmer_cell.csv](https://github.com/labsyspharm/mcmicro-flowSOM/files/13041214/CRC--mesmer_cell.csv)
[markers.txt](https://github.com/labsyspharm/mcmicro-flowSOM/files/13041204/markers.txt)

```
workflow:
  start-at: downstream 
  downstream: [flowsom, fastpg]
  fastpg-model: ./flowsom4/markers.txt
  flowsom-model: ./flowsom4/markers.txt
options:
  flowsom: -n 15
  fastpg: -k 25
modules:
  downstream:
  - name: fastpg
    model: -m
  - name: flowsom
    model: -m
```

Thank you
